[[language]]
name = "python"
language-servers = ["ty", "ruff"]

[[language]]
name = "matlab"
language-servers = ["matlab-ls"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.matlab-ls]
command = "bun"
args = ["run", "/Users/felixperfler/.matlab/MATLAB-language-server/out/index.js", "--stdio"]

